### ISSUE TITLE
FileNotFoundException: KahaDB/db-1.log (No such file or directory)

### ISSUE THREAD

**Issue by Gzerox** [cptactionhank/docker-atlassian-bamboo#8]
Hello everybody, 
first thing: I'm not sure if this problem is related to my enviroment or something else, but hope someone can help me.

**What i use:**
* Docker for Windows (CE) 17.06.0-ce-win18 (12627)
* Kitematic (GUI)
* WIndows 10 (x64)

**What i did:**
* With Kitematic downloaded and created a container with docker-atlassian-bamboo: https://hub.docker.com/r/cptactionhank/atlassian-bamboo/
* Setup my volumes
* Run the container

Now, everything looks fine, the container run correctly , i can also reach the home page.
Setup basic info in order to allow container to connect my DB:
* Esternal DB 
* PostgreSQL
* User-Password

Installation process starts, when suddenly:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'broker' defined in class path resource [applicationContextJMSServer.xml]: Cannot create inner bean 'org.apache.activemq.broker.BrokerService#7eff4605' of type [org.apache.activemq.broker.BrokerService] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.activemq.broker.BrokerService#7eff4605': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /var/atlassian/bamboo/jms-store/bamboo/KahaDB/db-1.log (No such file or directory)
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1147)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:295)
... 66 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.activemq.broker.BrokerService#7eff4605': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /var/atlassian/bamboo/jms-store/bamboo/KahaDB/db-1.log (No such file or directory)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:299)
... 78 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /var/atlassian/bamboo/jms-store/bamboo/KahaDB/db-1.log (No such file or directory)
at org.apache.activemq.broker.BrokerService.postConstruct(BrokerService.java:567)
at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
... 83 more
Caused by: java.io.FileNotFoundException: /var/atlassian/bamboo/jms-store/bamboo/KahaDB/db-1.log (No such file or directory)
at java.io.RandomAccessFile.open0(Native Method)
at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
at org.apache.activemq.util.RecoverableRandomAccessFile.<init>(RecoverableRandomAccessFile.java:44)
at org.apache.activemq.store.kahadb.disk.journal.DataFile.openRandomAccessFile(DataFile.java:92)
at org.apache.activemq.store.kahadb.disk.journal.DataFileAccessor.<init>(DataFileAccessor.java:47)
at org.apache.activemq.store.kahadb.disk.journal.DataFileAccessorPool$Pool.openDataFileReader(DataFileAccessorPool.java:52)
at org.apache.activemq.store.kahadb.disk.journal.DataFileAccessorPool.openDataFileAccessor(DataFileAccessorPool.java:130)
at org.apache.activemq.store.kahadb.disk.journal.Journal.recoveryCheck(Journal.java:464)
at org.apache.activemq.store.kahadb.disk.journal.Journal.start(Journal.java:306)
at org.apache.activemq.store.kahadb.MessageDatabase.load(MessageDatabase.java:474)
at org.apache.activemq.store.kahadb.MessageDatabase.doStart(MessageDatabase.java:297)
at org.apache.activemq.store.kahadb.KahaDBStore.doStart(KahaDBStore.java:218)
at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
at org.apache.activemq.store.kahadb.KahaDBPersistenceAdapter.doStart(KahaDBPersistenceAdapter.java:227)
at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
at org.apache.activemq.broker.BrokerService.doStartPersistenceAdapter(BrokerService.java:675)
at org.apache.activemq.broker.BrokerService.startPersistenceAdapter(BrokerService.java:659)
at org.apache.activemq.broker.BrokerService.start(BrokerService.java:623)
at org.apache.activemq.broker.BrokerService.autoStart(BrokerService.java:578)
at org.apache.activemq.broker.BrokerService.postConstruct(BrokerService.java:565)
... 89 more
2017-07-07 10:18:39,706 ERROR [http-apr-8085-exec-6] [DefaultDispatcherErrorHandler] Exception occurred during processing request: Unable to instantiate Action, com.atlassian.bamboo.ww2.actions.setup.SetupDatabaseConnectionAction,  defined for 'performSetupDatabaseConnection' in namespace '/setup'Error creating bean with name 'decoratingErrorAccessor' defined in class path resource [applicationContext.xml]: Cannot resolve reference to bean 'decoratedErrorDetailsFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'decoratedErrorDetailsFactory' defined in class path resource [applicationContext.xml]: Cannot resolve reference to bean 'agentManager' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'agentManager' defined in class path resource [applicationContextManagers.xml]: Cannot create inner bean 'com.atlassian.bamboo.buildqueue.manager.AgentManagerImpl#f50e00d' of type [com.atlassian.bamboo.buildqueue.manager.AgentManagerImpl] while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'broker' defined in class path resource [applicationContextJMSServer.xml]: Cannot create inner bean 'org.apache.activemq.broker.BrokerService#7eff4605' of type [org.apache.activemq.broker.BrokerService] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.activemq.broker.BrokerService#7eff4605': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /var/atlassian/bamboo/jms-store/bamboo/KahaDB/db-1.log (No such file or directory) - action - file:/opt/atlassian/bamboo/atlassian-bamboo/WEB-INF/classes/struts.xml:452:128
```

BUT, if i login on docker:

```
$ cd /var/atlassian/bamboo/jms-store/bamboo/KahaDB
$ ls -l
total 1
-rwxr-xr-x 0 root root 33554432 Jul  1 21:16 db-1.log
-rwxr-xr-x 1 root root        8 Jul  1 21:16 lock

$ cat db-1.log
cat: db-1.log: No such file or directory
```

At this point:
* My web application is completely broken (i can't access anymore)
* No table on DB were created.

**Comment by cbromberg** [comment]
Hi, when you use the docker container the bamboo process will be run under user daemon, but the file we you are showing in ls -l is owned by root

Are you mounting the filesystem from outside the container?

**Comment by Gzerox** [comment]
Hello, thanks for answering.
Actually, i'm using Volumes on "Kitematic" in order to be able to store logs externally and so on my "volumes tab" i've the following:

![image](https://user-images.githubusercontent.com/2865058/28039241-cd19fcac-65c1-11e7-8d41-b14d3e50a920.png)

**Comment by cbromberg** [comment]
Hi, I am using docker-compose to mount these drives on a CoreOs host and have no problems. I have no experience with docker on windows or Kitematic at all, but a quick google seems to indicate that this might well be a windows specific issue.

**Comment by chetwatkins** [comment]
Hello, Did you happen to figure out how to fix this by chance? I am running into the exact same issue when using a windows share drive as the volume mount location. It creates the lock, the log says there is no db-1.log and it never creates my sql server db's.

The user shows as bamboo.
`-rwxrwxrwx. 1 bamboo bamboo 33554432 Sep 15 02:33 db-1.log
-rwxrwxrwx. 1 bamboo bamboo        8 Sep 15 02:33 lock`

I got the ID of 1000 from bamboo on the container and gave the permissions to the share. I know this part is working since if i do not give that ID permissions, it does not even create all the files and directories.
